title: BK Home

background: center / cover no-repeat url("/background.png") fixed

views:

  #view1
#- title: Home
  - icon: mdi:home-assistant
    id: home
    background: radial-gradient(black, skyblue)
    theme: dark-mode
    cards:
      - type: entity-filter
        entities:
          - entity: device_tracker.dsbrot
            name: DsBrot
          - entity: binary_sensor.motion_all
            name: Motion
          - entity: binary_sensor.floor_door
            name: Castle
          - entity: input_boolean.bedtime
            name: 
          - entity: input_boolean.wintertime
            name: 
        state_filter:
          - 'home' 
          - 'work'
          - 'not_home'
          - 'on'
          - 'off'
        card:
          type: glance
          #title: What happen at home
      - type: glance
        entities:
          - entity: sensor.balkon_temp
            name: Temp
          - entity: sensor.balkon_luftfeuchtigkeit 
            name: LF
          - entity: sensor.balkon_luftdruck
            name: Druck
#      - type: conditional
#        conditions:
#          - entity: binary_sensor.motion_all
#            state: "on"
#        card:
      - type: glance
        entities:
          - entity: climate.bath_1_0
            name: Bath
          - entity: climate.bedroom_1_0
            name: Bed
          - entity: climate.living_1_0
            name: Balkon
          - entity: climate.living_2_0
            name: Couch
          - entity: climate.living_3_0
            name: Klavier
          - entity: climate.room3_1_0
            name: Work
          - entity: climate.room4_1_0
            name: Ankleide
      - type: weather-forecast
        entity: weather.home
        name: Wetter BK
#      - type: picture-entity
#       image: https://www.home-assistant.io/images/default-social.png
#       entity: group.all_lights
#      - type: history-graph
#        entities:
#          - entity: device_tracker.device
#        hours_to_show: 4
      - type: entities
        title: Sonos
        entities:
          - entity: media_player.sonos_speaker_bath
            name: 'Sonos One Bath'
          - entity: media_player.sonos_speaker_bedroom
            name: 'Sonos One Bedroom'
          - entity: media_player.sonos_speaker_living
            name: 'Sonos One Living'
          - entity: media_player.sonos_speaker_kitchen
            name: 'Sonos One Kitchen'
          - entity: media_player.sonos_speaker_room3
            name: 'Sonos One Work'
          - entity: media_player.sonos_speaker_room4
            name: 'Sonos One Ankleide'
          - entity: media_player.sonos_speaker_wc
            name: 'Sonos One WC'
#      - type: media-control
#        entity: media_player.sonos_speaker_bath
#      - type: media-control
#        entity: media_player.sonos_speaker_bedroom
#      - type: media-control
#        entity: media_player.sonos_speaker_living
      - type: entities
        title: Alles
        entities:
          - entity: group.all_automations
            name: Alle Automatisierungen
          - entity: group.all_devices
            name: Alle Devices
          - entity: group.all_lights
            name: Alle Lichter
#          - entity: group.all_locks
#            name: Alle Locks
#          - entity: group.all_remote
#            name: Alle Fernbedienungen
          - entity: group.all_scripts
            name: Alle Skripte
#          - entity: group.all_switches
#            name: Alle Schalter
#      - type: entities
#        entities:
#          - type: weblink
#            url: 'http://192.168.2.10/admin'
#            name: PiHole
#          - type: weblink
#            url: 'http://192.168.2.159'
#            name: Homematic


  #view2
  - icon: mdi:television
    title: Living
    cards:
      - type: markdown
        title: Wohnzimmer
        content: >
          ... entspann dich
      - type: glance
        entities:
          - entity: sensor.living_temp
            name: Temp
          - entity: sensor.living_luftfeuchtigkeit 
            name: LF
          - entity: sensor.living_luftdruck
            name: Druck
          - entity: binary_sensor.living_door_2_0
            name: Schublade
          - entity: binary_sensor.living_door_1_0
            name: Balkon Tuer
          - entity: binary_sensor.living_door_3_0
            name: Klavier Fenster
          - entity: binary_sensor.living_door_4_0
            name: Dachfenster
          - entity: binary_sensor.living_switch_1_0
            name: Switch 1
      - type: entities
        title: Licht
        entities:
          - entity: light.living_stripe_tv
            name: Stripe
          - entity: light.living_1_0
            name: Kleine Lampe
          - entity: light.living_2_0
            name: Mittlere Lampe
          - entity: light.living_panel_1_0
            name: Panel
      - type: entities
        title: Heizung
        entities:
          - entity: climate.living_1_0
            name: Heizung Balkon
          - entity: climate.living_2_0
            name: Heizung Couch
          - entity: climate.living_3_0
            name: Heizung Klavier 
      - type: entities
        title: Media Player
        entities:
          - entity: media_player.living_denonavr
            name: Denon AVR
          - entity: media_player.living_kodi
            name: Kodi
          - entity: media_player.living_tv
            name: Samsung TV
      - type: conditional
        conditions:
          - entity: media_player.living_tv
            state: "on"
        card:
          type: media-control
          entity: media_player.living_tv

  #view3
  - icon: mdi:sleep
    title: Bedroom
    cards:
      - type: markdown
        title: Schlafzimmer
        content: >
          ... schlaf gut
      - type: glance
        entities:
          - entity: sensor.sleeping_temp
            name: Temp
          - entity: sensor.sleeping_luftfeuchtigkeit 
            name: LF
          - entity: sensor.sleeping_luftdruck
            name: Druck
          - entity: binary_sensor.bedroom_motion
            name:
          - entity: binary_sensor.bedroom_switch_1_1
            name:
          - entity: binary_sensor.bedroom_switch_1_2
            name:
          - entity: switch.bedroom_power_handy
            name: Handy
          - entity: switch.bedroom_power_tv
            name: TV
          - entity: binary_sensor.bedroom_door_1_0
            name: Fenster
          - entity: binary_sensor.bedroom_door_2_0
            name: Dachfenster
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                title: Time
                entities:
                  - entity: input_datetime.alarm_1_mon_time
                    name: Mon
                  - entity: input_datetime.alarm_1_tue_time
                    name: Tue
                  - entity: input_datetime.alarm_1_wed_time
                    name: Wed
                  - entity: input_datetime.alarm_1_thu_time
                    name: Thu
                  - entity: input_datetime.alarm_1_fri_time
                    name: Fri
                  - entity: input_datetime.alarm_1_sat_time
                    name: Sat
                  - entity: input_datetime.alarm_1_sun_time
                    name: Sun
              - type: entities
                title: Days
                entities:
                  - entity: input_boolean.alarm_1_mon
                    name: "Mon"
                    icon: " "
                  - entity: input_boolean.alarm_1_tue
                    name: "Tue"
                    icon: " "
                  - entity: input_boolean.alarm_1_wed
                    name: "Wed"
                    icon: " "
                  - entity: input_boolean.alarm_1_thu
                    name: "Thu"
                    icon: " "
                  - entity: input_boolean.alarm_1_fri
                    name: "Fri"
                    icon: " "
                  - entity: input_boolean.alarm_1_sat
                    name: "Sat"
                    icon: " "
                  - entity: input_boolean.alarm_1_sun
                    name: "Sun"
                    icon: " "
          - type: entities
            entities:
              - type: call-service
                icon: mdi:settings
                name: Settings
                action_name: "show/hide"
                service: input_boolean.toggle
                service_data:
                  entity_id: input_boolean.alarm_1_settings
      - type: conditional
        conditions:
          - entity: input_boolean.alarm_1_settings
            state: "on"
        card:
          type: entities
          title: Wecker - Settings
          show_header_toggle: false
          entities: 
            - input_boolean.alarm_1_notify
            - input_number.alarm_1_notify_offset_min
            - input_boolean.alarm_1_snoozing
            - input_number.alarm_1_snoozing_min
            - input_boolean.alarm_1_wakeup_light
            - input_number.alarm_1_light_offset_min
            - input_boolean.alarm_1_wakeup_music
            - input_number.alarm_1_music_offset_min
            - input_boolean.alarm_1_wakeup_climate
            - input_number.alarm_1_climate_offset_min
      - type: entities
        title: Licht
        entities:
          - entity: light.bedroom_stripe_bed
            name: Stripe
          - entity: light.bedroom_1_0
            name: Grosse Lampe
          - entity: light.bedroom_2_0
          - type: divider
            style:
              height: 1px
              width: 84%
              margin-left: auto
              margin-right: 0
              background: '#62717b'
          - entity: light.xiaomigw
            name: Xiaomi GW
      - type: entities
        title: Heizung
        entities:
          - entity: climate.bedroom_1_0
            name: Heizung Schlafzimmer
      - type: entities
        title: Sensoren
        entities:
          - entity: sensor.xiaomigw_illumination
            name:
          - entity: sensor.bedroom_motion_lux
            name:
      - type: entities
        title: Media Player
        entities:
          - entity: media_player.bedroom_tv
            name: Samsung TV

  #view4
  - icon: mdi:shower
    title: Bath
    cards:
      - type: markdown
        title: Bad
        content: >
          ... Zeit fuer dich
      - type: glance
        entities:
          - entity: sensor.bath_temp
            name: Temp
          - entity: sensor.bath_luftfeuchtigkeit 
            name: LF
          - entity: sensor.bath_luftdruck
            name: Druck
          - entity: binary_sensor.bath_motion
            name: 
          - entity: sensor.bath_motion_lux
            name: 
      - type: entities
        title: Licht
        entities:
          - entity: light.bath_stripe_mirror
            name: Licht Spiegel
      - type: entities
        title: Heizung
        entities:
          - entity: climate.bath_1_0
            name: Heizung Bad

  #view5
  - icon: mdi:pot
    title: Kitchen
    cards:
      - type: markdown
        title: Kueche
        content: >
          ... Genuss pur
      - type: glance
        entities:
          - entity: binary_sensor.kitchen_motion
            name: Motion
          - entity: sensor.kitchen_motion_lux
            name: Lux
      - type: entities
        title: Licht
        entities:
          - entity: light.kitchen_panel_1_0
            name: Panel

  #view5
  - icon: mdi:calendar-multiple-check
    title: Work
    cards:
      - type: markdown
        title: Arbeitszimmer
        content: >
          ... sei effizient
      - type: glance
        entities:
          - entity: sensor.room3_temp
            name: Temp
          - entity: sensor.room3_luftfeuchtigkeit 
            name: LF
          - entity: sensor.room3_luftdruck
            name: Druck
      - type: entities
        title: Licht
        entities:
          - entity: light.room3_panel_1_0
            name: Panel
      - type: entities
        title: Heizung
        entities:
          - entity: climate.room3_1_0
            name: Heizung

  #view5
  - icon: mdi:tshirt-crew
    title: Ankleide
    cards:
      - type: markdown
        title: Ankleidezimmer
        content: >
          ... freie Wahl
      - type: glance
        entities:
          - entity: sensor.room4_temp
            name: Temp
          - entity: sensor.room4_luftfeuchtigkeit 
            name: LF
          - entity: sensor.room4_luftdruck
            name: Druck
      - type: entities
        title: Heizung
        entities:
          - entity: climate.room4_1_0
            name: Heizung

  #view5
  - icon: mdi:human-male-female
    title: wc
    cards:
      - type: markdown
        title: Gaesteklo
        content: >
          ... Haende waschen ;)
      - type: glance
        entities:
          - entity: binary_sensor.wc_motion
            name: Motion
          - entity: sensor.wc_motion_lux
            name: Lux
      - type: entities
        title: Licht
        entities:
          - entity: light.wc_stripe_mirror
            name: Spiegel

  #view5
  - icon: mdi:arrow-expand-all
    title: floor
    cards:
      - type: markdown
        title: Flur
        content: >
          ... fuer jeden was dabei
      - type: entity-filter
        entities:
          - entity: binary_sensor.floor_motion_0_0
            name: Flur Motion 
          - entity: binary_sensor.floor_motion_1_0
            name: Flur 1 Motion 
          - entity: binary_sensor.floor_motion_2_0
            name: Flur 2 Motion 
        state_filter:
          - "off"
          - "on"
        card:
          type: glance
      - type: entities
        title: Licht
        entities:
          - entity: light.floor_0_0
            name: Ganzer Flur
          - entity: light.floor_panel_1_0
            name: Panel
          - entity: light.floor_panel_2_0
            name: Panel
          - entity: light.floor_panel_3_0
            name: Panel

#  #view5
#  - icon: mdi:basket
#    title: abstellkammer
#    cards:
#      - type: markdown
#        title: Abstellkammer
#        content: >
#          ... fuer jeden was dabei


#  #view6
#  - icon: mdi:map
#    title: Karte
#    cards:
#      - type: markdown
#        title: Karte
#        content: >
#          ... heute hier morgen dort
#      - type: map
#        title: Karte
#        entities:
#          - entity: zone.home
#          - entity: zone.work
#          - entity: device_tracker.device1
